'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Btns
    Public Property grupo As String
    Public Property template_id As String
    Public Property bpath As String
    Public Property click_event As String
    Public Property classe As String

    Public Overridable Property Templates As Templates

End Class
