'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Campos
    Public Property Campo As String
    Public Property linha As Boolean
    Public Property Tag As String

    Public Overridable Property Campos_Descricoes As ICollection(Of Campos_Descricoes) = New HashSet(Of Campos_Descricoes)
    Public Overridable Property Campos_ImagensUrl As Campos_ImagensUrl
    Public Overridable Property Campos_Length_Limites As Campos_Length_Limites
    Public Overridable Property Campos_Methods As ICollection(Of Campos_Methods) = New HashSet(Of Campos_Methods)
    Public Overridable Property Campos_Modulos As ICollection(Of Campos_Modulos) = New HashSet(Of Campos_Modulos)
    Public Overridable Property Campos_Seq As ICollection(Of Campos_Seq) = New HashSet(Of Campos_Seq)
    Public Overridable Property Campos_DataMinMax As Campos_DataMinMax
    Public Overridable Property Campos_MinMax As Campos_MinMax
    Public Overridable Property Tbls_Sorts As ICollection(Of Tbls_Sorts) = New HashSet(Of Tbls_Sorts)
    Public Overridable Property Tbls_PageInfos As ICollection(Of Tbls_PageInfos) = New HashSet(Of Tbls_PageInfos)

End Class
