'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Campos_Seq
    Public Property Modulo As String
    Public Property Campo As String
    Public Property Sequencia As Short

    Public Overridable Property Campos As Campos
    Public Overridable Property Campos_Seq_Panels As ICollection(Of Campos_Seq_Panels) = New HashSet(Of Campos_Seq_Panels)

End Class
