'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Campos_Seq_Panels
    Public Property Modulo As String
    Public Property Campo As String
    Public Property Panel As String

    Public Overridable Property Campos_Seq As Campos_Seq

End Class
