'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Campos_Descricoes
    Public Property Campo As String
    Public Property Linguagem As Byte
    Public Property Descricao As String
    Public Property Placeholder As String
    Public Property Informacao As String

    Public Overridable Property Campos As Campos

End Class
