'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Campos_MinMax
    Public Property Campo As String
    Public Property Tipo As String
    Public Property Valor_Minimo As Decimal
    Public Property Valor_Maximo As Decimal
    Public Property Definir_Minimo As Boolean
    Public Property Definir_Maximo As Boolean
    Public Property Edicao As Boolean
    Public Property Formato As String
    Public Property Data_Inclusao As Date
    Public Property Data_Alteracao As Date
    Public Property Local_Alteracao As Long
    Public Property Data_Exclusao As Nullable(Of Date)
    Public Property excluido As Boolean

    Public Overridable Property Campos As Campos

End Class
