'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Campos_ImagensUrl
    Public Property Campo As String
    Public Property Descricao_Default As String
    Public Property Descricao_Back As String

    Public Overridable Property Campos As Campos

End Class
