'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ComboList
    Public Property Linguagem As Byte
    Public Property Tipo As String
    Public Property Codigo As String
    Public Property Ordem As Byte
    Public Property Descricao As String
    Public Property qCadastros As Boolean
    Public Property qProdutos As Boolean
    Public Property qTributacoes As Boolean
    Public Property qNFe As Boolean
    Public Property qParametros As Boolean
    Public Property qMovimentacoes As Boolean
    Public Property qEstoque As Boolean
    Public Property Data_Inclusao As Date
    Public Property Data_Alteracao As Date
    Public Property Local_Alteracao As Long
    Public Property Data_Exclusao As Nullable(Of Date)
    Public Property excluido As Boolean

End Class
