'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Mensagens
    Public Property Linguagem As Byte
    Public Property Id As String
    Public Property Funcao As Boolean
    Public Property Campo As Boolean
    Public Property Comum As Boolean
    Public Property Grupo As String
    Public Property Mensagem As String

End Class
