'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Tbls
    Public Property tbl As String
    Public Property tbl_referencia As String
    Public Property start_name As String
    Public Property table_name As String
    Public Property show_header As Boolean
    Public Property pauta_index As Byte
    Public Property fitcontent As Boolean
    Public Property resize As Boolean
    Public Property drilldown As Boolean
    Public Property image As Boolean
    Public Property preview As Boolean
    Public Property red_button As Boolean
    Public Property table_width As String
    Public Property bpath As String
    Public Property rowspan As Byte
    Public Property template_header As String
    Public Property template_itens As String
    Public Property template_options As String

    Public Overridable Property Tbls_ClickEvents As ICollection(Of Tbls_ClickEvents) = New HashSet(Of Tbls_ClickEvents)
    Public Overridable Property Tbls_Modulos As ICollection(Of Tbls_Modulos) = New HashSet(Of Tbls_Modulos)
    Public Overridable Property Tbls_PageInfos As Tbls_PageInfos
    Public Overridable Property Tbls_Querys As Tbls_Querys
    Public Overridable Property Tbls_Sorts As ICollection(Of Tbls_Sorts) = New HashSet(Of Tbls_Sorts)

End Class
