'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Tbls_ClickEvents
    Public Property tbl As String
    Public Property tipo As String
    Public Property click_event As String

    Public Overridable Property Tbls As Tbls

End Class
