'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Tbls_Sorts
    Public Property tbl As String
    Public Property Campo As String
    Public Property Campo_BD As String
    Public Property Order_From_Select As String
    Public Property optional_order As String
    Public Property compactar_descricao As Boolean

    Public Overridable Property Campos As Campos
    Public Overridable Property Tbls As Tbls

End Class
