'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Tbls_Querys
    Public Property tbl As String
    Public Property From_ As String
    Public Property Select_ As String
    Public Property Where_ As String
    Public Property GroupBy_ As String
    Public Property Count_Total As String

    Public Overridable Property Tbls As Tbls

End Class
