'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Tbls_PageInfos
    Public Property tbl As String
    Public Property Quantidade_Linhas_Pagina As Short
    Public Property Campo_Default As String
    Public Property Label_Id_NotFound As String

    Public Overridable Property Campos As Campos
    Public Overridable Property Tbls As Tbls

End Class
