'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Temas
    Public Property Codigo_Tema As Integer
    Public Property roundbutton As Boolean
    Public Property Data_Inclusao As Date
    Public Property Data_Alteracao As Date
    Public Property Local_Alteracao As Long
    Public Property Data_Exclusao As Nullable(Of Date)
    Public Property excluido As Boolean

    Public Overridable Property Temas_Colors As ICollection(Of Temas_Colors) = New HashSet(Of Temas_Colors)
    Public Overridable Property Temas_Css As ICollection(Of Temas_Css) = New HashSet(Of Temas_Css)

End Class
