'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Workers
    Public Property Id As Integer
    Public Property Nome As String
    Public Property Email As String
    Public Property Cargo As String
    Public Property Salario As Decimal
    Public Property Data_Contratacao As Date

End Class
